GET https://jsonplaceholder.typicode.com/posts
###
POST https://jsonplaceholder.typicode.com/posts
# header name: header value

Content-Type: application/json

{
    "title": "New Post",
    "body": "This is a new post."
}